### ISSUE TITLE
Transaction and Database missing Clone, FdbError doesn't have Fail in 0.4+

### ISSUE THREAD

**Issue by Aioxas** [Clikengo/foundationdb-rs#176]
Just curious if they were replaced for a better way, if so, if there are examples that I can refer to for these changes.

**Comment by Speedy37** [comment]
Previously transaction was an atomic reference counted pointer to an FDBTransaction.
This was fine, as we needed an Owned and easy/fast to clone transaction for its usage this futures 0.1.

Now that async/await is available, we can leverage the borrowed approach and use a reference to the transaction. If required you can still either Rc or Arc the transaction, but that commit/abort/reset all requires either an owned Transaction or a mutable one. Which can be done by calling either: `Arc::make_mut`, `Arc::get_mut` or `Arc::try_unwrap`.

Protecting those method was required to prevent documented by the fdb C Api undefined behavior.

For example: 

>  fdb_transaction_commit() must have been called on transaction and the resulting future must be ready and not an error before this function is called, or the behavior is undefined.

> Be careful if you are using fdb_transaction_reset() and fdb_transaction_cancel() concurrently with the same transaction. Since they negate each other’s effects, a race condition between these calls will leave the transaction in an unknown state.

**Comment by Speedy37** [comment]
About `Fail`, I can reintroduce it as an optional feature if required.

**Comment by Aioxas** [comment]
I see, so I should Rc/Arc the database/transactions if I am moving it around. Thanks for the insight!

**Comment by Speedy37** [comment]
Personally I'm using `&Transaction`, in order to prove at compile time that when I commit there is no way another thread is writing to it.

**Comment by Speedy37** [comment]
Btw, Database::transact is the recommended way to manipulate the database.
See `Database::transact_boxed` and `Database::transact_boxed_local` for much easier to use versions of it.

This is implemented with a trait so once GAT is working we can use Database::transact directly.

**Comment by Aioxas** [comment]
Wasn't sure if I should be making a new thread for this, but how come tx.get and .commit are awaited while other tx methods aren't? such as set and such. More curious than anything

**Comment by Speedy37** [comment]
`get` is async because there is a roundtrip to the database in order to get some data.
`commit` is async because it must wait for the database to finish handling all previous `set` and actually commit then.
`set` is sync because it only "send" the data, there is no need to wait for it, the next `commit` or `get` (of the affected value) will do it.
