### ISSUE TITLE
Transaction::get_range hangs

### ISSUE THREAD

**Issue by giacomocariello** [Clikengo/foundationdb-rs#189]
When I set a non-null end range key, the get_range method hangs indefinitely. I wrote an example to reproduce:

Cargo.toml:

```
[package]
name = "fdbtest"
version = "0.1.0"
edition = "2018"

[dependencies]
foundationdb = { version = "^0.4.2", default-features = false, features = [ "embedded-fdb-include", "fdb-6_2" ] }
foundationdb-sys = { version = "^0.4.2", default-features = false, features = [ "embedded-fdb-include", "fdb-6_2" ] }
futures = "^0.3.4"

[[bin]]
name = "fdbtest"
path = "src/main.rs"
```

src/main:

```
use std::borrow::Cow;

fn main() {
    let _network = foundationdb::boot().expect("Shouldn't break");
    let db = foundationdb::Database::from_path("./fdb.cluster").expect("Database shouldn't break");
    let trx = db.create_trx().expect("Transaction shouldn't break");
    let range_begin = foundationdb::KeySelector::first_greater_or_equal(Cow::Borrowed("A".as_bytes()));
    let range_end = foundationdb::KeySelector::first_greater_than(Cow::Borrowed("Z".as_bytes()));
    //let range_end = foundationdb::KeySelector::first_greater_than(Cow::Borrowed("".as_bytes()));
    let range = foundationdb::RangeOption::from((range_begin, range_end));
    println!("Beginning of query");
    futures::executor::block_on(trx.get_range(&range, 1, false)).expect("Query shouldn't fail");
    println!("End of query");
}
```
Execution never reach second println.

If I uncomment the second range_end line, execution completes successfully.

I tried to collect transaction logs through tracing, but nothing gets printed regarding this transaction, probably because it never reaches completion.

Any clue why this happens?

**Comment by Speedy37** [comment]
I just tested your code, there is no hang.

Are you sure you are connected to the cluster. Sometime that hangs.
Does get_key hang too?
Can you add `drop(_network);` at the end of main to ensure network is at least running up to that point.
In your code, get_range is the first async code.

Foundationdb version, Operating system, rustc version ?

**Comment by Speedy37** [comment]
Also can you try `fdbcli -c ./fdb.cluster` to validate your cluster file is ok.

**Comment by giacomocariello** [comment]
Okay, dumb me. Due to a mistake in fdb.cluster path selection, the client was connecting to a server that had no database created. IMHO, on a design level, the above test program should have panicked before returning a transaction.

**Comment by Speedy37** [comment]
There is no way in the current foundationdb C API to know about this.
https://apple.github.io/foundationdb/api-c.html#network

**Comment by Speedy37** [comment]
From my understanding, foundationdb would auto unlock itself as soon as the database is ready.

**Comment by giacomocariello** [comment]
Yup, it wasn't meant as a criticism of rust implementation: the design problem, if one exists, belongs to the underlying C library. I was just wondering wether I should post something on FoundationDB forum as well.
I'm closing the issue since there's nothing to fix at this level.

**Comment by Speedy37** [comment]
Don't worry I didn't took it like that.
Yeah, you should post about that either on the FoundationDB forum or their github.
