### ISSUE TITLE
Typo in bindingtester

### ISSUE THREAD

**Issue by kurayama** [Clikengo/foundationdb-rs#193]
`TUPKE_PACK_WITH_VERSONSTAMP` should probaby be `TUPLE_PACK_WITH_VERSIONSTAMP`

https://github.com/Clikengo/foundationdb-rs/blob/94b05f34f50a653734b53fff29078003b75fd4f8/foundationdb-bindingtester/src/main.rs#L236

**Comment by Speedy37** [comment]
Good catch.

This also validate what we can see in the binding tester code coverage: https://coveralls.io/builds/31055210/source?filename=foundationdb-bindingtester/src/main.rs#L1191 

TuplePackWithVersionstamp is not tested and is part of the `api` bindingtest suite, but it's only run is specified to.
