### ISSUE TITLE
Support u128/i128 in tuple layer

### ISSUE THREAD

**Issue by akhilles** [Clikengo/foundationdb-rs#198]
Implement `TuplePack` and `TupleUnpack` for u128 and i128. This would be useful for 16-bytes ids which are somewhat common.

**Comment by Speedy37** [comment]
This is already the case on master: https://clikengo.github.io/foundationdb-rs/foundationdb/tuple/trait.TuplePack.html#impl-TuplePack-for-u128

**Comment by akhilles** [comment]
Ah, sorry should've checked first. Thanks for the quick response!
