### ISSUE TITLE
Implement std::error::Error for FdbError in v0.4

### ISSUE THREAD

**Issue by nielspardon** [Clikengo/foundationdb-rs#200]
@Speedy37: Could we get your commit also for v0.4? That would simplify my life a lot :-)

https://github.com/Clikengo/foundationdb-rs/blob/add16c5f76a55fdd0d0c15753e58b5e4030b4bfb/foundationdb/src/error.rs#L81

**Comment by Speedy37** [comment]
I suggest you migrate to 0.5 that just got released

**Comment by nielspardon** [comment]
Works for me. Thanks!
