### ISSUE TITLE
foundationdb::boot in v0.5 is very hard to use

### ISSUE THREAD

**Issue by coadler** [Clikengo/foundationdb-rs#202]
It's very hard to use the new `boot`/`boot_async` functions for starting up the network routine. Nothing I plug in plays well with the `panic::catch_unwind`, so I've settled on just parking the thread in the provided function and unparking at the end of my `main()`.

It's usage is also quite confusing. Coming from `v0.4`, I wasn't aware that all the code had to be run inside of the closure because there's no docs specifying how to use it. If you pass an empty closure in and try to use the db as normal, transactions return a bunch of `Broken promise` errors which are misleading.

As the simplest reproduction, I can't even use a `oneshot`.
```toml

[dependencies]
tokio = { version = "0.2", features = ["full"] }
foundationdb = { git = "https://github.com/Clikengo/foundationdb-rs", branch = "master" }
```
```rust
use tokio::sync::oneshot;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let (tx, rx) = oneshot::channel::<String>();
    let net = std::thread::spawn(|| {
        foundationdb::boot(|| {
            tx.send("booted!".into());
        });
    });

    println!("{}", rx.await?);
    Ok(())
}
```
```
error[E0277]: the type `std::cell::UnsafeCell<std::sync::atomic::AtomicUsize>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
   --> src/repr.rs:7:9
    |
7   |         foundationdb::boot(|| {
    |         ^^^^^^^^^^^^^^^^^^ `std::cell::UnsafeCell<std::sync::atomic::AtomicUsize>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
    |
   ::: /home/colin/.cargo/git/checkouts/foundationdb-rs-2d9865a5eba0ba56/add16c5/foundationdb/src/lib.rs:116:42
    |
116 | pub fn boot<T>(f: impl (FnOnce() -> T) + std::panic::UnwindSafe) -> T {
    |                                          ---------------------- required by this bound in `foundationdb::boot`
    |
    = help: within `tokio::sync::oneshot::Inner<std::string::String>`, the trait `std::panic::RefUnwindSafe` is not implemented for `std::cell::UnsafeCell<std::sync::atomic::AtomicUsize>`
    = note: required because it appears within the type `tokio::loom::std::atomic_usize::AtomicUsize`
    = note: required because it appears within the type `tokio::sync::oneshot::Inner<std::string::String>`
    = note: required because of the requirements on the impl of `std::panic::UnwindSafe` for `std::sync::Arc<tokio::sync::oneshot::Inner<std::string::String>>`
    = note: required because it appears within the type `std::option::Option<std::sync::Arc<tokio::sync::oneshot::Inner<std::string::String>>>`
    = note: required because it appears within the type `tokio::sync::oneshot::Sender<std::string::String>`
    = note: required because it appears within the type `[closure@src/repr.rs:7:28: 9:10 tx:tokio::sync::oneshot::Sender<std::string::String>]`
```

Is there a technical reason why we need to run our code inside the `boot` function? I much preferred the `v0.4` boot API.

cc @Speedy37

**Comment by Speedy37** [comment]
The issue with 0.4 api is that it allow safe rust code to cause UB. The same logic should still be available in 0.5 but requires unsafe code, if I recall correctly.

**Comment by akhilles** [comment]
Since `NetworkAutoStop::drop` will be called even if the application code panics, is this
```rust
// v0.5
foundationdb::boot(|| {
    run_application_code();
});
```
any safer than
```rust
// v0.4
let network_builder = FdbApiBuilder::default().build().expect("fdb api initialized");
let network_stop_if_dropped = network_builder.boot().expect("fdb network to run");
run_application_code();
drop(network_stop_if_dropped);
```
?

**Comment by Speedy37** [comment]
The boot method was introduced by the pull #179 in order to fix #170.
I dont remember what caused the auto drop to not work in that case, I should have documented it.

**Comment by Speedy37** [comment]
I did dig a little, the reason is that there are multiple ways to not prevent drop from beeing called, the issue in #170  was cause by: 

```
lazy_static! {
    static ref ENV: fdb::api::NetworkAutoStop = fdb::boot().expect("fdb boot failed");
}
```

Which means, once the network is started, drop won't ever be called.

One can also "forget" the guard.

**Comment by Speedy37** [comment]
You can still have the old behavior with https://clikengo.github.io/foundationdb-rs/foundationdb/api/struct.NetworkBuilder.html#method.build:

```rust
let network_builder = FdbApiBuilder::default().build().expect("fdb api initialized");
let (runner, cond) = network_builder.build().expect("fdb network runners");

let net_thread = std::thread::spawn(move || {
    unsafe { runner.run() }.expect("failed to run");
});

// Wait for the foundationDB network thread to start
let fdb_network = cond.wait();

// do some work with foundationDB, if a panic occur you still **MUST** catch it and call
// fdb_network.stop();

// You **MUST** call fdb_network.stop() before the process exit
fdb_network.stop().expect("failed to stop network");
net_thread.join().expect("failed to join fdb thread");
```

**Comment by Speedy37** [comment]
Sorry, I did some new investigations and found a way to make the 0.5 `run` API hit undefined behavior:

 - spawn a thread
 - in that thread execute the `boot(|| { sleep_ms(100000000) })`
 - exit the process
 - the network thread is never correctly stopped.

So I reverted the recommanded way of starting the foundationdb network thread to `0.4` style but it now requires the unsafe block to use it.
